# Project
version=2.2.11
group=mangomilk.carryon

# Common
minecraft_version=1.21.1
mod_name=CarryOnRevamped
mod_author=TeamMangoMilk
credits=Originally created by Tschipp and Purplicious_Cow
mod_id=carryon
license=GNU LGPLv3
description=CarryOnRevamped is a simple mod that improves game interaction by allowing players to pick up, carry, and place single block Tile Entities using only their empty hands.
minecraft_version_range=[1.21.1, 1.21.2)
# Forge
forge_version=52.1.0
forge_loader_version_range=[52,)
forge_version_range=[52,)
parchment_mappings=2024.07.28-1.21
//forge_ats_enabled=true

# Fabric
fabric_version=0.116.7+1.21.1
fabric_loader_version=0.16.2
parchment_mappings_fabric=1.21:2024.07.28

# Neoforge
neoforge_version=21.1.217
neoforge_loader_version_range=[4,)
neogradle.subsystems.parchment.minecraftVersion=1.21
neogradle.subsystems.parchment.mappingsVersion=2024.07.28


# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.java.home=C:\\Program Files\\Android\\openjdk\\jdk-21.0.8

mixinextras_version=0.3.6
